# Generated by Django 3.2.4 on 2021-06-02 21:29

from django.db import migrations, models
import webhooksocket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('hook_ident', models.CharField(db_index=True, default=webhooksocket.models.random_ident, max_length=64, unique=True, verbose_name='Webhook Unique Identifier')),
                ('socket_ident', models.CharField(db_index=True, default=webhooksocket.models.random_ident, max_length=64, unique=True, verbose_name='Websocket Unique Identifier')),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
