# Generated by Django 3.2.4 on 2021-06-02 21:07

from django.db import migrations, models
import webhooksocket.models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooksocket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='hook_ident',
            field=models.CharField(db_index=True, default=webhooksocket.models.random_ident, max_length=64, unique=True, verbose_name='Webhook Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='socket_ident',
            field=models.CharField(db_index=True, default=webhooksocket.models.random_ident, max_length=64, unique=True, verbose_name='Websocket Unique Identifier'),
        ),
    ]
